### ISSUE TITLE
NetworkManager-libnm may have compatibility issue between container and host

### ISSUE THREAD

**Issue by yuvalif** [nmstate/kubernetes-nmstate#1]
Possible solutions:
(1) add operator to check version on host (```yum info NetworkManager-libnm```) and fetch the right image of the container to be used in the daemon-set (several images will have to be built)
(2) another option is to not install NetworkManager-libnm in the container at all, and mount the needed objects from the host into the container
(3) third option would be to install full NetworkController at container with host network config, so no NetworkController sould be needed in the host.

**Comment by phoracek** [comment]
kubernetes-nmstate is used to setup default host networking. Although this is done on day-2, it has to survive reboots and be configured sooner than Kubernetes is started (since it provides the default network needed by Kubernetes). This is why (3) is not a viable option.

I'm not sure if I understand option (2). I don't think it is possible to use libnm built for different system inside the container.

If we ever run into a problem with non-compatible system, we should consider (1), possibly with node selectors (although I'm not sure how to detect on Kubernetes level).

**Comment by SchSeba** [comment]
related to (2) I think we can maybe mount the host fs and use chroot to start the kubernetes-nmstate process in the host file system that way it will use the same libs like the host.

**Comment by phoracek** [comment]
But it has dependencies on python modules AFAIK :/ We would need to get rid of those. Also it would be very funny container then :D

**Comment by qinqon** [comment]
@thaller give us a way to check version with dbus:
```
15:05 <thaller> quiquell, see busctl --json pretty call org.freedesktop.NetworkManager /org/freedesktop org.freedesktop.DBus.ObjectManager GetManagedObjects 
15:05 <thaller> on the org/freedesktop/NetworkManager object
```

**Comment by phoracek** [comment]
Should not be an issue if one of the support NM versions is used on the host.

https://github.com/nmstate/kubernetes-nmstate/blob/master/CONTRIBUTING.md#networkmanager-compatibility
