### ISSUE TITLE
Default route at bridge e2e test is not working

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#192]
We have mark it as pending, but we need to debug it, fix it and un-pending it.

**Comment by qinqon** [comment]
We have better results now, let's monitor it this week.

**Comment by qinqon** [comment]
it's working now for 2 years is enough for monitoring :-)

**Comment by rhrazdil** [comment]
I'm opening this again as the issue appears now and then in the handler lane.
Also, very similar issue appears when the same scenario is done with ovs-bridge.

More investigation is needed, but the node reboot seems to be the common divisor here.

**Comment by rhrazdil** [comment]
After taking closer look at this issue I think I have come to understanding what is going on.
The test scenario goes as follows:
1. Create NNCP
2. Restart node (do not wait for restart to complete)
3. t1 = time.Now()
4. Wait for a NNS LastSuccessfulUpdate timestamp to be >= t1  (so wait until timestamp of nns is newer than time right after rebooting the node)

I believe the problem is that when the node restarts, the Reconcile of the one NNCP happens before NNS is updated with the state that lacks the configuration that the NNCP defines.
In a little bit more detail:
1. Create NNCP
Between 1 and 2, NNS contains the configuration with the NNCP applied
2. Restart node
Now the node comes up which sends create event to the NNCP watcher and it runs Reconcile of that NNCP, that reconcile finishes before NNS was updated, meaning NNS contains the state with the NNCP configuration all the time the node was down.

At the end of reconcile, we force NNS refresh, but because the state of the existing NNS is the same as the current state of the node, nothing is updated because of this condition: 
https://github.com/nmstate/kubernetes-nmstate/blob/main/controllers/node_controller.go#L88

I propose removing the check of the NNS update timestamp from the test 
https://github.com/nmstate/kubernetes-nmstate/blob/main/test/e2e/handler/default_bridged_network_test.go#L145
and substitute it with a `Consistently` check verifying that the desired state is kept after the node reboot

@qinqon what do you think?
