### ISSUE TITLE
KUBEVIRT_NUM_NODES=2 with multiple nics make cluster-up not working

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#52]
It just startup node01 and not node02.

**Comment by phoracek** [comment]
@qinqon It fails because of passed QEMU argument. We pass additional arguments to connect our node VM to a secondary network. The problem is, that it take one argument passed to all nodes, while each node should get a unique value. I'm afraid there is no way around it, only dropping the NIC. Maybe we could add a patch to kubevirt/kubevirtci.

**Comment by qinqon** [comment]
@phoracek we can address that in this PR too, but this is only about correctly exercising the regex.

**Comment by phoracek** [comment]
@qinqon this issue says "cluster-up not working", which I believe will remain true even after #53. Let's keep that PR for regex only

**Comment by qinqon** [comment]
Humm that's right, then I remove the "Closes" from it.

**Comment by qinqon** [comment]
Add new test that just creates bridge and one node and we test both, so we need multinode to test it.

Also bypass this if we are not in multinode env.

**Comment by phoracek** [comment]
This has been solved. Multiple NICs now work on kubevirtci, thanks to @qinqon
